# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: chenwuai'blog
subtitle: ''
description: 'chnwuai blog'
keywords: 'Hexo,Hexo主题,Blog,博客'
author: chenwuai
language: zh-CN
timezone: ''
avatar: https://i.loli.net/2020/07/02/JKNsSczEb68Rlvj.gif

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  测试: test
tag_map:
  测试: test

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''


# volantis theme config
# 网站图标，更多尺寸等图标请使用import方式批量导入
favicon: https://cdn.jsdelivr.net/gh/chenchenwuai/assets/images/favicon.ico

live2d:
  enable: true
  scriptFrom: local
  model:
    # use: live2d-widget-model-wanko #模型选择
    use: live2d-widget-model-hibiki #模型选择
  display:
    position: left  #模型位置
    width: 110       #模型宽度
    height: 260      #模型高度
  mobile:
    show: false      #是否在手机端显示

theme_config: 
  #--------------------------------------
  # volantis theme config
  #--------------------------------------

  # Navigation Bar
  navbar:
    logo: # choose [img] or [icon + title]
      img: 
      icon:
      title: chenwuai
  #--------------------------------------

  layout:
    # The following can be written in `blog/source/_data/layout.yml`
    # 文章列表（主页、自定义的列表）布局
    on_list:
      # 列表中每一篇文章的meta信息
      meta: [title, author, category, date, wordcount, top]
      # 列表类页面的侧边栏
      sidebar: [blogger, category, tagcloud]
      # read more button
      readmore: 阅读全文 <i class="fas fa-chevron-right"></i>
    # 页面布局
    on_page:
      # 文章页面主体元素，你也可以在页面的Front-matter中设置
      body: [article, comments]
      # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
      # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
      # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
      meta:
        header: [title, author, category, date,wordcount, top]
        footer: [updated, tags, btns, share]
      # 文章页面的侧边栏
      sidebar: [qrcode, toc]
    # 文章布局，参数继承自 on_page
    on_post:
      # 文章页脚，自动在每一篇文章末尾添加
      article_footer: [references, related_repos, copyright, donate]
    # 其他的页面布局暂时等于 on_list


  style:
    fontfamily:
      logofont:
        fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'Varela Round'
        url: https://cdn.jsdelivr.net/gh/chenchenwuai/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
        weight: normal
        style: normal
      bodyfont:
        fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
        name: 'UbuntuMono'
        url: https://cdn.jsdelivr.net/gh/chenchenwuai/cdn-fonts/UbuntuMono/UbuntuMono-Regular.ttf
        weight: normal
        style: normal
        offset: 0.1rem # Correct baseline for zh-CN
      codefont:
        fontfamily: 'Menlo, UbuntuMono, Monaco'
        # name: 'Monaco'
        # url: https://cdn.jsdelivr.net/gh/chenchenwuai/cdn-fonts/Monaco/Monaco.ttf
        # weight: normal
        # style: normal
    color:
      # site: '#21232F' # Website background color
      # site_inner: '#fff' # Text color inside the website background
      site_footer: '#fff' # Footer text color inside the website background
      # card: '#444' # Card background color
      # text: '#fff' # The color of the text on the card.
      # theme: '#ff9800' # Main color
      # link: '#1BCDFC' # Link color
      # hover: '#ff5722' # Link highlight color
      # inner: '#333' # Text color inside the button
      # block: '#555' # Block color
      # inlinecode: '#555' # Inline code color
      # codeblock: '#555' # Codeblock color
      # p: '#ccc' # Paragraph color
  #--------------------------------------

  # cover
  cover:
    scheme: docs # docs, blog
    display:
      home: true
      archive: true
      others: false # can be written in front-matter 'cover: true'
    logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
    title: chenwuai
    subtitle: 'chenwuai blog'
    search: # search bar placeholder
    features:
      - name: 首页
        # icon: 
        url: /
      - name: 文章
        # icon: fas fa-book
        url: archives/
      - name: 分类
        # icon: fas fa-folder-open
        url: categories/
      - name: 标签
        # icon: fas fa-folder-open
        url: tags/
  #--------------------------------------
  
  # meta library
  meta:
    # 文章标题
    title: # 暂无配置
    # 默认文章作者（可在front-matter中覆盖）
    author:
      avatar: https://i.loli.net/2020/07/02/JKNsSczEb68Rlvj.gif
      name: chenwuai
      url: /
    # 文章创建日期
    date:
      icon: fas fa-calendar-alt
      # title: '发布于：'
      title: ''
      format: 'YYYY-MM-DD HH:mm' # 日期格式 http://momentjs.com/docs/
    # 文章更新日期
    updated:
      icon: fas fa-edit
      title: '更新于：'
      format: 'YYYY-MM-DD HH:mm' # 日期格式 http://momentjs.com/docs/
    # 文章评论数量：只支持 valine
    valinecount:
      icon: fas fa-comment-dots
      desc: '条评论'
    # 文章分享 
    share:
      - id: qq
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
      - id: weibo
        img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
      # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
      #   img: 
      # - id: telegram
      #   img: 
  #--------------------------------------

  footer:
    # layout of footer: [aplayer, social, license, info, copyright]
    layout: [aplayer, social, license, info, copyright]
    social:
      # - icon: fas fa-rss
      #   url: atom.xml
      - icon: fas fa-envelope
        url: mailto:zccjxx62@gmail.com
      - icon: fab fa-github
        url: https://github.com/chenchenwuai
      - icon: fas fa-headphones-alt
        url: https://music.163.com/#/user/home?id=110896778
    # copyright: '[Copyright © 2017-2020 Mr. X](https://xaoxuu.com)'
    copyright: '[Copyright © 2017-2020 chenwuai]'
    # You can add your own property here. (Support markdown, for example: br: '<br>')
    br: '<br>'
  #--------------------------------------

  plugins:
    # Message
    message: https://cdn.jsdelivr.net/gh/inkss/common@1.3/hexo/js/message.min.js

    # Slide Background
    backstretch:
      enable: true
      js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
      position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
      shuffle: true         # shuffle playlist
      duration: 20000       # Duration (ms)
      fade: 1500            # fade duration (ms) (Not more than 1500)
      images:               # For personal use only. At your own risk if used for commercial purposes !!!
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/35F12181-F0E9-45BD-B134-37E4B4A660CF.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

    # npm i --save hexo-wordcount
    wordcount: true

  # widget library
  widget:
    # The following can be written in `blog/source/_data/widget.yml`
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://i.loli.net/2020/07/02/JKNsSczEb68Rlvj.gif
      shape: circle # circle, rectangle
      url: 
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true

    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/

    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'

    # copyright widget (valid only in articles)
    copyright:
      class: copyright
      display: [desktop, mobile] # [desktop, mobile]
      blockquote: true
      # permalink: '本文永久链接是：'
      content:
        - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
        # - permalink  

      # qrcode widget
      donate:
        class: qrcode
        display: [] # [desktop, mobile]
        height: 64px  # Automatic height if not set
        fancybox: true
        images:
          - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
          - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
      
